"""Paste text for BP_ImmDlgSubsystem: clear the dialogue body layer's stale notifies after it is switched off.

Why (nonstop footsteps after a conversation, Nexus 2026-09-25 / 10-02): a disabled post-process anim instance is no
longer updated, but the mesh still dispatches its queued notifies every frame
(USkeletalMeshComponent::ConditionallyDispatchQueuedAnimEvents has no disabled check), and only an update or a
re-initialise empties that queue. If the conversation ends on a frame where the layer's walk played a footstep
(AnimNotify_AnyFootOnGround on the ar walk animations), that footstep fires every frame until the next conversation
switches the layer back on. Re-enabling runs SetDisablePostProcessBlueprint(false) -> InitializeAnimation ->
UninitializeAnimation -> NotifyQueue.Reset; so one tick after the layer goes off we switch it on and straight off
again (the layer is not evaluated that frame, the same state as the dialogue-start re-enable, which is safe).

Nodes (comment box "Body layer: flush stale notifies"), wired by hand to the existing box "Body layer: dialogue only":
  "body layer on".then  -> SET BodyLayerWasOn = true                       ("layer was on")
  "body layer off".then -> Branch "layer just went off?" (BodyLayerWasOn)
        true  -> SET BodyLayerWasOn = false -> SET BodyLayerFlush = true   (flush on the next tick)
        false -> Branch "flush now?" (BodyLayerFlush)
                   true -> SET Disable Post Process Blueprint = false ("flush: re-init clears stale notifies")
                        -> SET Disable Post Process Blueprint = true  ("flush: off again")
                        -> SET BodyLayerFlush = false
  Target of both flush SETs: Get Player Character -> Mesh (inside the paste).
Variables BodyLayerWasOn / BodyLayerFlush (Boolean): add_flush_vars.py.
Usage: python gen_subsystem_notify_flush.py <export.t3d> <out.txt>
  <export.t3d> = harness export_t3d.py of /ImmersiveDialogue/Runtime/BP_ImmDlgSubsystem (nodes are lifted from it).
"""
import os
import re
import sys

HARNESS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "..",
                       "stalker2-immersive-campfires", "harness", "tools", "t3d")
sys.path.insert(0, HARNESS)
from bp_t3d import comment_box, write  # noqa: E402
from t3d_lift import Lifted, link  # noqa: E402

src, out = sys.argv[1], sys.argv[2]
EP = "BP_ImmDlgSubsystem:EventGraph."
X0, Y0 = 2700, 1760


def comment_line(text):
    def f(line):
        return re.sub(r'NodeComment="[^"]*"', f'NodeComment="{text}"', line)
    return f


def bool_var(node, var, value=None, comment=""):
    """Lift the ReinitTried get/set node as a get/set of `var` (resolved by name; MemberGuid dropped)."""
    def f(line):
        line = line.replace("ReinitTried", var)
        line = re.sub(r",MemberGuid=[0-9A-F]+", "", line)
        if value is not None and f'PinName="{var}"' in line:
            line = re.sub(r'(?<!Autogenerated)DefaultValue="[^"]*"', f'DefaultValue="{value}"', line)
        return line
    return f


def lifted(name, path, x, y, replace=None, comment=None):
    n = Lifted(src, EP + path, name, x, y, replace=replace)
    # pin_ids were keyed before `replace` renamed pins; key them by the final names
    n.pin_ids = {m.group(2): m.group(1) for m in (re.search(r'PinId=([0-9A-F]+),PinName="([^"]+)"', l)
                                                  for l in n.lines) if m}
    if comment is not None:
        if any(l.strip().startswith("NodeComment=") for l in n.lines):
            n.lines = [comment_line(comment)(l) for l in n.lines]
        else:
            i = next(k for k, l in enumerate(n.lines) if l.strip().startswith("NodeGuid="))
            n.lines[i:i] = ["   bCommentBubbleVisible=True", f'   NodeComment="{comment}"']
    return n


set_was_on = lifted("K2Node_VariableSet_9101", "K2Node_VariableSet_5", X0, Y0,
                    bool_var(None, "BodyLayerWasOn", "true"), "layer was on")
get_was = lifted("K2Node_VariableGet_9102", "K2Node_VariableGet_4", X0 - 20, Y0 + 400, bool_var(None, "BodyLayerWasOn"))
br_was = lifted("K2Node_IfThenElse_9103", "K2Node_IfThenElse_9", X0 + 200, Y0 + 256, comment="layer just went off?")
set_was_off = lifted("K2Node_VariableSet_9104", "K2Node_VariableSet_5", X0 + 560, Y0 + 220,
                     bool_var(None, "BodyLayerWasOn", "false"), "layer was off")
set_flush = lifted("K2Node_VariableSet_9105", "K2Node_VariableSet_5", X0 + 900, Y0 + 220,
                   bool_var(None, "BodyLayerFlush", "true"), "flush next tick")
get_flush = lifted("K2Node_VariableGet_9106", "K2Node_VariableGet_4", X0 + 380, Y0 + 640, bool_var(None, "BodyLayerFlush"))
br_flush = lifted("K2Node_IfThenElse_9107", "K2Node_IfThenElse_9", X0 + 560, Y0 + 500, comment="flush now?")
pp_on = lifted("K2Node_VariableSet_9108", "K2Node_VariableSet_7", X0 + 900, Y0 + 500,
               comment="flush: re-init clears stale notifies")
pp_off = lifted("K2Node_VariableSet_9109", "K2Node_VariableSet_8", X0 + 1280, Y0 + 500, comment="flush: off again")
set_flush_off = lifted("K2Node_VariableSet_9110", "K2Node_VariableSet_5", X0 + 1660, Y0 + 500,
                       bool_var(None, "BodyLayerFlush", "false"), "flush done")
player = lifted("K2Node_CallFunction_9111", "K2Node_CallFunction_1", X0 + 380, Y0 + 800)
mesh = lifted("K2Node_VariableGet_9112", "K2Node_VariableGet_0", X0 + 700, Y0 + 800)

link(get_was, "BodyLayerWasOn", br_was, "Condition")
link(br_was, "then", set_was_off, "execute")
link(set_was_off, "then", set_flush, "execute")
link(br_was, "else", br_flush, "execute")
link(get_flush, "BodyLayerFlush", br_flush, "Condition")
link(br_flush, "then", pp_on, "execute")
link(pp_on, "then", pp_off, "execute")
link(pp_off, "then", set_flush_off, "execute")
link(player, "ReturnValue", mesh, "self")
link(mesh, "Mesh", pp_on, "self")
link(mesh, "Mesh", pp_off, "self")

nodes = [set_was_on, get_was, br_was, set_was_off, set_flush, get_flush, br_flush, pp_on, pp_off, set_flush_off,
         player, mesh]
lines = comment_box("EdGraphNode_Comment_9100", X0 - 100, Y0 - 120, 2200, 1100, "Body layer: flush stale notifies")
for n in nodes:
    lines += n.text()
write(out, lines)
print(f"wrote {out}: {len(nodes)} nodes")
